package br.ufpa.app.android.amu.v1.integracao.classes;

public enum TipoFuncao {
    CADASTRO_MEDICAMENTOS,
    LISTA_MEDICAMENTOS,
    HORARIO_MEDICAMENTOS,
    USO_MEDICAMENTOS,
    ESTOQUE_MEDICAMENTOS,
    PERFIL_USUARIO,
    CHAMADA_TELA,
    PESQUISA_MEDICAMENTOS,
    CONSULTA_MEDICAMENTOS,
    DETALHES_MEDICAMENTO,
}
